#!/usr/bin/env bash
# command to install nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo ""Holberton School"" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload
